keep koin module initialization for dataTest module
when proguard is applied we are unable to inject the in memory database
variant for the fragment tests.

`java.lang.NoSuchMethodError: No static method b(Ljava/lang/Class;)Lkotlin/reflect/KClass;`

this is caused by proguard removing both the `kotlin.reflect` and parts
of the `org.koin.core` package.